### ISSUE TITLE
No title 

### ISSUE THREAD

**Issue by erosalie** [ravenscroftj/joplin-hypothesis#6]
Any idea what might be causing the plugin to pull the annotations without a headline? They are all titled [Object object].

**Comment by djsudduth** [comment]
Adding to this! Titles are missing - plus, private notes are not syncing.

**Comment by ravenscroftj** [comment]
Thanks, this issue should now be fixed in 0.1.2.  I will address private note syncing in a separate issue and a new release

**Comment by djsudduth** [comment]
@ravenscroftj - thanks for fixing the title. The imported notes still say "Web annotation by null" vs "Web annotation by myusername"

I hope you add private notes soon!! Much needed!
